상태 관리로 메뉴 관리하기
InSeong-So/TS-moonbucks-menu pull request #7
Opened 2021-12-01 14:26 UTC by InSeong-So

1. 현재 any 타입이 상당히 많이 쓰였습니다. 이유는 redux 내부 로직을 정의하는데 설계가 완벽하지 않다보니...ㅠㅠ 이 부분은 점진적으로 수정해보겠습니다.
2. 상태가 수정되면 렌더링이 되어야 하는데, 이 렌더링을 어느 부분에서 pub/sub을 해야 부드럽고 이슈 없는 앱이 될지 고민중입니다. 현재는 각 컴포넌트의 메서드에서 역할이 끝나면 수동으로 this.render()를 호출하고 있습니다.
3. 로컬 스토리지의 확장이 필요합니다. 보안의 문제와 많은 예외 처리가 누락되어 있습니다.
4. redux-saga를 구현하고자 하는데.... 시간이 부족해서 우선 reducers는 카테고리 메뉴를 불러오고(백엔드 데이터가 없으므로 하드코딩입니다) 카테고리가 변경될 때만 사용하도록 했습니다.

2021-12-03 16:16 UTC, SINHOLEE reviewed
일차리뷰... 졸려서 잘게요

2021-12-03 16:16 UTC, SINHOLEE commented on index.ts
> +const router = new Router({
아니 라우터까지 구현하셨나요.... 대단;

2021-12-03 16:16 UTC, SINHOLEE commented on src/components/MenuPage.ts
> +      <ul id="${this._id}-menu-list" class="mt-3 pl-0"></ul>
이부분에서 메뉴리스트 컴포넌트가 바인딩된다라는 표시가 있으면 템플릿 분석할때 조금 더 수월할거같은데 다른 방법 없을까요?

저는 

```
 <ul id="${this._id}-menu-list" class="mt-3 pl-0">
{{MenuList}}
</ul>
```

라고 표현했는데 이게 그렇게 좋은방법은 아닌거같더라구요. 가독성을 위해 필요없는 코드쪼가리를 써버리는 거였는데 다른 방법이 없을까요?

2021-12-03 16:16 UTC, SINHOLEE commented on src/components/MenuPage.ts
> +    const { pages, params } = <ComponentProp>this.$props;
const { pages, params } = <ComponentProp>this.$props;

에서 타입단언 안하면 pages랑 params 타입 유실되나요? 유실 안될거같은데 단언을 계속 하시는 이유가 있어요?

2021-12-03 16:16 UTC, SINHOLEE commented on src/components/MenuPage.ts
> +    this.store.dispatch(selectedCategory(<string>params));
params에도 단언하셧네요 제가 단언데 집착하는 이유는 사실 타입단언은 최소한으로 사용해야지 추론으로 인한 미연의 문제 방지를 기대할 수 있는데 단언을 계속 사용하면 타입스크립트를 쓰는 이점을 조금 버리는 느낌이 들기 때문입니다..ㅎㅎㅎ

2021-12-03 16:16 UTC, SINHOLEE commented on src/App.ts
> +    new MenuPage('main', {
여기서는 메뉴페이지컴포넌트에 pages 인자에 error를 할당해서 에러페이지를 구현하셨는데요.
`pageNotFound`가 미리 선언하지 않은 라우터 url로 들어왔을경우 에러페이지를 보여주기 위한 라우팅이라면
new ErrorPage라고 새로운 페이지 컴포넌트를 만들어야 한다고 생각해요

그리고 MenuPage에서는 에러페이지를보여주는 경우는 오직 잘못된 selected정보가 들어왔을때만 나타나야하지 않을까요?
```
this._isLocationError = !selected.id;
```


로만 관리해야한다고 생각해요 그럼 사실 `isLocationError`보다는 `isRuntimeError` 정도로 네이밍 하면 더 좋을것 같습니다.

2021-12-03 16:16 UTC, SINHOLEE commented on src/packages/storage/LocalState.ts
> +  constructor() {
상속받은 친구에 추가적인 생성자 로직이 없으면 생략가능하다고 알고있어용~

2021-12-03 16:16 UTC, SINHOLEE commented on src/packages/storage/LocalState.ts
> +class LocalState extends Storage<ParangStorageKey | string> {
Storage로 추상화를 했으면 AuthStorage랑 MenuStorage 두개로 나눠서 관리하면 더 명확하게 관리할 수 있을거 같아요!

2021-12-03 16:16 UTC, SINHOLEE commented on src/packages/storage/Storage.ts
> +  protected get(key: T): string | null {
제생각에는 get할때 null이 반환되면 우리가 의도한 결과가 아니게 되자나요?
그러니까 가장 코어한 부분(컴포넌트에서 불러오는 데이터는 localStorage에서 get 되는 string)이 제대로 불러와지지 않는다면 에러를  throw해서 어플리케이션 단의 로직에 전파해서 원인을 알려야한다고 생각해요.

그러니까
```
  protected get(key: T): string {
    const res = this.storage.getItem(this.getOriginKey(key));
    if(typeof res !=='string'){
        throw new Error(`${key}가 키인 로컬 스토리지는 없습니다.`)
    }
    return res;
}
```

이렇게 작성하면 디버깅할때 수월해지지 않을까요?

2021-12-03 16:16 UTC, SINHOLEE commented on src/packages/storage/Storage.ts
> +    keys.forEach(key => this.clearItem(this.getOriginKey(key) as T));
as T 가 왜 필요하죵? clearItem메서드는 void일텐뎅...as T 없으면 에러뜨나요?

2021-12-03 16:17 UTC, SINHOLEE commented on src/packages/storage/Storage.ts
> +  protected get(key: T): string | null {
3. 예외처리 누락이 여기였군...호호

2021-12-04 14:59 UTC, xianeml reviewed
components/MenuList, MenuPage 파일 위주로 리뷰 남겼습니닷
파랑님 코드 읽다보면 시간이 훌쩍 가네요..!🤓

2021-12-04 14:59 UTC, devmhl commented on src/components/MenuList.ts
> +    if (isUnique) return alert('이미 등록되어 있는 메뉴입니다.');
등록된 메뉴 중복 체크 좋네요! trim()을 사용해 입력값 공백 조건까지 체크해주면 좋을 것 같습니다👍

2021-12-04 14:59 UTC, devmhl commented on src/components/MenuList.ts
> +  }
입력값 유효성 검사까지 신경쓰시다니! 이런 디테일 많이 배워야겠습니다 ㅎㅎ
여기도 trim 사용해서 공백체크 필요할 것 같습니닷

2021-12-04 14:59 UTC, devmhl commented on src/components/MenuList.ts
> +    const updatedItemName = prompt('메뉴 이름을 수정하시겠어요?', text) ?? text;
`??` 연산자에 대해 새로 알아갑니다ㅎㅎ null 또는 undefined만 검사해주는군요

2021-12-04 14:59 UTC, xianeml commented on src/components/MenuPage.ts
> +        const targetItemIndex = <string>$span.getAttribute('index');
`targetItemIndex` 사용 시 `<string>`타입 단언 후 +기호를 붙여 숫자 타입으로 변환해서 사용하신 이유가 있을까요?
```js
const targetItemIndex = Number($span.getAttribute('index'));
```
Number 함수 사용 시 가독성이 더 좋을 것 같다는 생각이 듭니다!

2021-12-04 14:59 UTC, xianeml commented on src/components/MenuPage.ts
> +        event.preventDefault();
이벤트 리스너를 리스트 전체에 등록해서 matches()로 요소를 비교하는 간단한 방법이 있군요!! 👏  
이 클릭이벤트에서 `event.preventDefault();`는 어떤 동작을 막기 위해 사용되었을까요??

2021-12-04 16:51 UTC, SINHOLEE requested changes
어휴 이미 많이 코드변화가 있을텐데 과거의 코드에 주저리주저리 많이해서 헷갈리실거같아요. 최대한 이해하고 코멘트 작성하려고 해서 오래걸렸네요....ㅠㅠ 제 어플이나 빨리 만들어야하는데 파랑님 코드가 흥미로워서 이것부터 하게 되네요! 너무 말이 많아서 거를건 거르시고, 제 의견과 다른부분이 있으면 꼭! 이야기 나누었으면 좋겠습니다.

2021-12-04 16:51 UTC, SINHOLEE commented on src/packages/redux/common/createActionType.ts
> +const createActionType = (action: string) => {
이친구 역할은 제가 이해한바로는 actionType의 비동기 로직을 한번에 관리하려고 만들어 놓으신거 같은데 맞나요? pending fulfilled rejected 를 각각 대응하신거같은데 맞다면 함수명을 조금 더 명확하게 짓는게 좋을거같아요! 세개를 반환하니까 types나... 음 세트니까 group? union? 따위를 넣으면 좋을것 같고... 아니다 types에서 복수의 느낌이 나니까 union이나 group은 빼죠. 음 프로미스객체를 다루는 거니까 async나 promise를 붙이는게 좋을거같아요...

createAsyncActionTypes, createPromiseActionTypes가 명확한 이름이지 않을까요!

2021-12-04 16:51 UTC, SINHOLEE commented on src/packages/redux/reducers/menus.ts
> +export const selectedCategory = (data: string) => ({
state 안에 categories중에서 id가 data랑 같은 category 하나를 set하는것이기 때문에 setSelectedCategory로 하시거나 아니면 동사원형인 selectCategoryById로 하시는게 어떠신가요? 아니면 `export const selectedCategory = (data: {categoryId:string}) => ({ `으로 인자의 키 벨류로 받게하면 selectCategory로 byId를 빼도 가독성이 좋아질것같아요! 

data가 string으로만타입지정되어있으면 사실 categoryProps에서 Id인지 text인지 모르겠으니까요!

2021-12-04 16:51 UTC, SINHOLEE commented on src/types/redux.ts
> +  [index: string | symbol]: any;
index는 타입에서 사용하는 예약어인가요? 뭐지...? 궁금해요!

2021-12-04 16:51 UTC, SINHOLEE commented on src/components/MenuList.ts
>      if (callback) callback(this.itemCount);
구조적으로 좀 문제있어보이는 부분이 눈에 띄어서 코멘트 남깁니다.

callback함수를 인자로 받는데 이건 잘 생각해보시면 굳이 인자로 받을 필요없는 친구입니다.
적어도 menuList 클래스에서 callback을 사용하는 모든 메서드에서는 callback이 가리키는 함수가 자기자신의 setMenuCount 메서드이므로 그냥 내부에서 호출하면 될것같습니다.

```
    this.render();
     this.setMenuCount(this.itemCount);
```

근데 애초에  callback함수를 쓰는 이유가 뭘까요?
제가 이해하기로는 무슨 행위를 할지 모르는 함수지만  나중에 실행하는 시점이 
```
    this.render();
    if (callback) callback(this.itemCount);
```
이때! 라는것 하나만은 백프로 알고 있을 때 쓰는거라고 이해하고 있어요.

그런데 파랑님은 추상화된콜백에 인자를 this.itemCount라고 지정해버려서 재사용성이 불가능한 함수로 써버렸네요
만약 callback을 실행시점fix의 역할로 사용하신다면 사용처(MenuPage)에서

```
menuList.insertItem('이름!',()=>{someService.anyMethod(인자1, 인자2, etc)})
```
처럼 다른 행위를 하게하는게 더 적합한 사용법이라 생각해요!

2021-12-04 16:51 UTC, SINHOLEE commented on src/components/MenuList.ts
> +    this._items[index] = soldOutItem;
이런로직들이 사실은 reducer안에 들어가있어야 겠죵!

2021-12-04 16:51 UTC, SINHOLEE commented on src/packages/dom/diffRender.ts
>    virtualDom.innerHTML = template;
음... 돔을 비교하기 위해서 돔을 생성해버리면 애초에 vDom을 관리하는 이유가 없어지게 되는거같아요....ㅠ 

새로운 돔을 그리기 전에 vdom으로 비교해서 바꿀필요가 있을때 비로소 real에 새 돔을 그려서 반영하는거자나요? 근데 애초에 비교를 위해 
```  
const virtualDom = <HTMLElement>realDom.cloneNode(true);
  virtualDom.innerHTML = template;
```
이렇게 하면 돔을 새로 그렸는데 그럼 비교해는 로직이 오히려 오버헤드지 않을까요?

2021-12-04 16:51 UTC, SINHOLEE commented on src/components/MenuPage.ts
> +        }
파랑님은 mount라는 메서드를 돔 생성 후 생성되어있는 돔을 조작해서 추가적인 로직을 수행할 수 있는 공간이라고 정의하신거죠? 이렇게 관리하면 문제는 없지만 아쉬운건 기껏  core component class를 만들었는데 그 분리된 기능을 제대로 이용하지 못해보인다는 것입니다...ㅠㅠ

저는 mount를 해당 컴포넌트의 template를 다 그리고 난 후 *해당 컴포넌트 안에 존재하는 돔 객체에 한해서* 돔을 select하고 조작하는 로직을 관리했었거든여

물론 파랑님처럼 상위 컴포넌트(MenuPage)에서 하위컴포넌트(MenuList)의 돔객체를 하위컴포넌트가 mount된 후! 접근한다면 문제될 건 없지만 menuPage의 역할보다는 menuList의 역할이라고 생각해요!

2021-12-04 16:51 UTC, SINHOLEE commented on src/components/MenuPage.ts
> +        }
참고로 파랑님 스타일은 nested한 mvc패턴에 가까운거 같아요 ㅎㅎㅎ 굳이 말하자면 Component가 controller역할을 한다고 해야하나

2021-12-05 07:53 UTC, InSeong-So commented on src/components/MenuPage.ts
> +    const { pages, params } = <ComponentProp>this.$props;
인터페이스를 동적 할당으로 선언해서, 객체 분해 할당 시 단언을 하지 않으면 일치하는 타입을 못 찾더라구요!

2021-12-05 07:55 UTC, InSeong-So commented on src/components/MenuPage.ts
> +      <ul id="${this._id}-menu-list" class="mt-3 pl-0"></ul>
그 부분을 고려하고 작성하는 중인데, 너무 커지더라구요ㅠㅠ
컨테이너 컴포넌트와 프레젠테이션 컴포넌트를 분리해서 제어를 할 생각으로 설계를 진행했습니다. 아직 구현은 못하구 있네요..! 백엔드 연동 시 확장과 개선을 진행해야 합니다ㅠ

2021-12-05 07:59 UTC, InSeong-So commented on src/components/MenuPage.ts
> +    this.store.dispatch(selectedCategory(<string>params));
맞습니다! 원래 단언을 사용하지 않고 추론 기능을 통해 가급적 타입을 선언하는 것을 피하는 게 이펙티브한 개발이죠!! 그 부분을 조금 더 고려해보겠습니다.

소프트웨어 설계가 아직 많이 미숙해서 개발초-중-후에 따른 구조가 계속 변경되고 있습니다. 그 잔해이죠...ㅠ 사유는 위에 언급한 바와 같습니다!

2021-12-05 10:15 UTC, InSeong-So commented on src/App.ts
> +    new MenuPage('main', {
오! 조언해주신 대로 구현해보겠습니다ㅎㅎ 렌더링을 어떻게 해결해야하나 고민하고 있다가 해결 못했었는데 감사합니당

2021-12-05 10:15 UTC, InSeong-So commented on src/packages/storage/LocalState.ts
> +  constructor() {
! 그대로 다 입력한 코드가 커밋에 있네요! 수정 뒤 올리겠습니다

2021-12-05 10:16 UTC, InSeong-So commented on src/packages/storage/LocalState.ts
> +class LocalState extends Storage<ParangStorageKey | string> {
ㅎㅎ맞아요 추후 로그인 부분도 구현을 해보려고 합니다. 메뉴에 대한 내용만으로 개발되어 부족한게 많네요ㅠ

2021-12-05 10:17 UTC, InSeong-So commented on src/packages/storage/Storage.ts
> +  protected get(key: T): string | null {
고쳐보겠습니다! 이 부분은 에러 캐치 모듈을 작성하던지, 공통 함수로 분리하여 처리 시키는 게 좋아보이네요!

2021-12-05 10:18 UTC, InSeong-So commented on src/packages/storage/Storage.ts
> +    keys.forEach(key => this.clearItem(this.getOriginKey(key) as T));
keys가 제네릭 Array라 단언이 없으면 에러가 납니다ㅠ

2021-12-05 10:18 UTC, InSeong-So commented on src/components/MenuList.ts
> +    if (isUnique) return alert('이미 등록되어 있는 메뉴입니다.');
제가 말씀드렸던 부분인데 누락시켰군요ㅠㅠ 감사합니다!

2021-12-05 10:19 UTC, InSeong-So commented on src/components/MenuList.ts
> +  }
메뉴에 대한 유효성 검사라 공통 함수로 분리하진 않았지만, 추상화가 가능해 보이므로 한 번 구현해 보려구요 ㅎㅎ 누락시킨 메서드에 대한 조언 감사합니다!

2021-12-05 10:20 UTC, InSeong-So commented on src/components/MenuList.ts
> +    const updatedItemName = prompt('메뉴 이름을 수정하시겠어요?', text) ?? text;
ㅎㅎ 널 병합 연산자는 truthy falsy에 대한 값을 체크하지 않기 때문에 가끔 사용합니다!

2021-12-05 10:28 UTC, InSeong-So commented on src/components/MenuPage.ts
> +        const targetItemIndex = <string>$span.getAttribute('index');
동일한 타입 변환이라 짧게 줄여 쓰는 것이 버릇인데, 확실히 가독성 면에서는 미현님 코드가 뚜렷하게 보이네요! 예시 감사합니다☺

2021-12-05 10:32 UTC, InSeong-So commented on src/components/MenuPage.ts
> +        event.preventDefault();
네네! 이벤트 위임을 통해 처리하였습니다!

`event.preventDefault();`는 필요 없는 코드가 맞구요ㅠㅠ 감사합니다!

2021-12-05 10:34 UTC, InSeong-So commented on src/packages/redux/common/createActionType.ts
> +const createActionType = (action: string) => {
디테일한 부분을 확인해주셔서 감사합니다! 이 함수는 말씀대로 비동기 로직을 간단하게 처리하려고 추상화를 한 함수입니다. 현재 작성 중인 코드는 createRequestActionTypes 로 API 통신에 사용하는 형태구요!
한 단계 더 추상화를 하거나 기능을 고도화하면 말씀해주신 함수가 더 좋아보이네요! 감사합니당👏

2021-12-05 10:40 UTC, InSeong-So commented on src/types/redux.ts
> +  [index: string | symbol]: any;
앗 아니에요ㅠ 동적 프로퍼티 할당으로 프로퍼티 키를 명시적으로 나타내야 했는데 index를 써두고 지우질 않았네요ㅠㅠ 수정하겠습니다!

2021-12-05 10:43 UTC, InSeong-So commented on src/packages/redux/reducers/menus.ts
> +export const selectedCategory = (data: string) => ({
동사 원형으로 하는 게 좋아보이네요! 이 함수명은 정말 생각을 많이 했는데, 상수로 선언한 식별자와 케이스만 바꾼 형태로 선언만 해두었습니다! 그래서 파라미터가 data로 되어있었어요ㅠ 수정하겠습니다!

2021-12-05 10:46 UTC, InSeong-So commented on src/components/MenuList.ts
>      if (callback) callback(this.itemCount);
음음 맞아요ㅠㅠ 원래 저 부분은 저렇게 작성하면 안되었는데, 구조를 생각하다가 현재 mount에 모든 로직이 집중되어 있는 형태입니다!

이건 절대 좋은 코드가 아니고 가독성과 컴포넌트 생성 시 중복으로 메모리 할당이 되니 문제가 많아지죠.

추상화 콜백도 본디 기능은 메뉴 리스트에서 선언한 함수를 부모 컴포넌트에서 제어하도록 설정해 놓았는데, 구조를 쪼개기 시작하면서 시간을 더 할애하지 못해 하나의 컴포넌트에 모든 로직이 집중된 상황입니다ㅠㅠ

조언 감사합니다! 이번 회차에서는 리듀서를 완성시키고, 기존에 혼자 작성했던 바닐라-saga를 추상화하면서 고쳐보겠습니다😆

2021-12-05 10:47 UTC, InSeong-So commented on src/components/MenuList.ts
> +    this._items[index] = soldOutItem;
이 부분 또한 리듀서를 작성하고 렌더링을 제어했어야 했는데 고민할 시간이 부족해서 스토어를 제대로 활용하지 않고 집중시킨 모습입니다ㅠㅠ 고쳐볼게요!

2021-12-05 10:48 UTC, InSeong-So commented on src/packages/dom/diffRender.ts
>    virtualDom.innerHTML = template;
아아 맞네요ㅠㅠ 이 부분은 여러 번 개선을 할 필요가 있어 보입니다. 감사합니다, 더 생각해볼게요!

2021-12-05 10:52 UTC, InSeong-So commented on src/components/MenuPage.ts
> +        }
기존 블랙커피 1기의 내용을 타입만 변환하면서 문법을 수정한 부분이라, 추상화가 제대로 이루어지지 않은 점은 확실합니다ㅠ

맞는 말씀이세요! 현재 저는 마스터 컴포넌트의 역할이 너무 과중화 되어있고, 중앙 집중형 저장소의 인젝션이 분리가 되어 있지 않습니다.
또한 이벤트를 핸들링하는 부분이 각 컴포넌트에 강하게 의존되어 있으므로, 렌더링이 구현되면 많은 문제가 생깁니다.
FLUX를 명확하게 구현하기 위해서 구조화를 조금 더 세밀히 다뤄야 하는데, 아직 심층 부분은 설계가 미흡한 감이 없잖아 있습니다. 이번 회차에 조금 더 다뤄보고 PR 할게요!

2021-12-05 16:13 UTC, SINHOLEE commented on src/components/MenuList.ts
>      if (callback) callback(this.itemCount);
사가까지... 머싯성...👀

2021-12-08 06:07 UTC, InSeong-So commented
> 이름!!! 복붙!!!! 실수!!!?

건강때문에 전 주차 피드백을 완벽히 적용하지 못해서 일부러 merge 없이 커밋했습니닷! PR명은 변경할게요 😇

2021-12-09 11:30 UTC, InSeong-So commented
1. ProxyObserver / EventBus를 분리한 동기?
2. http 모듈과 sagas의 강한 결합을 의도한 이유?
3. diff 적용을 구체화하면 상태/행위의 명확한 분리를 할 수 있을 것 같은데?
4. 각 컴포넌트가 mvc 자체를 구현하고 있어서 너무 복잡하다.
5. 우선 앱의 구조가 너무 복잡하고 읽기 힘들다. 최대한 단순하고 추상화 해야 한다.
6. mount 로직이 너무 많은 역할을 하며, 컴포넌트 역할이 아닌 이벤트(비즈니스 로직)도 제어하고 있어 너무 복잡하다.

2021-12-09 12:23 UTC, merged